import { Request, Response, NextFunction } from 'express';
import { User, Roadmap } from '../../models';
import agentOrchestrator from '../../services/ai/agentOrchestrator';
import { catchAsync, ApiResponse, AppError } from '../../utils';

export const generateRoadmap = catchAsync(
  async (req: Request, res: Response, next: NextFunction) => {
    const { goal } = req.body;
    const userId = req.user?.id;

    if (!goal) {
      return next(new AppError('Please provide a career goal or role', 400));
    }

    // 1. Fetch user profile for context
    const user = await User.findById(userId);
    if (!user) {
      return next(new AppError('User not found', 404));
    }

    try {
      // 2. Orchestrate multi-agent roadmap generation
      const roadmapData = await agentOrchestrator.orchestrateRoadmap(goal, {
        skills: user.skills,
        branch: user.department,
        year: user.year,
        bio: user.bio,
        resumeAnalysis: user.resumeAnalysis
      });

      // 3. Save to database
      const roadmap = await Roadmap.create({
        studentId: userId,
        title: `${goal} Roadmap`,
        targetRole: goal,
        weeks: roadmapData,
        status: 'active',
      });

      res.status(201).json(
        new ApiResponse(201, { roadmap }, 'Roadmap generated by AI Crew successfully')
      );
    } catch (error) {
      console.error('Roadmap Error:', error);
      return next(
        new AppError('AI Roadmap Designer encountered an issue. Please try again later.', 503)
      );
    }
  }
);

